# Notebook 2 - Modelos Lineares

Pipeline two-stage com Regressao Logistica no Stage 1, Regressao Linear no Stage 2 e XGBoost/Gradient Boosting como baselines.

In [1]:
from pathlib import Path
import sys

NOTEBOOK_DIR = Path.cwd()
UTILS_DIR = next(
    (candidate / "utils" for candidate in [NOTEBOOK_DIR, *NOTEBOOK_DIR.parents] if (candidate / "utils").is_dir()),
    None,
)
if UTILS_DIR is None:
    raise RuntimeError("Nao encontrei ml/notebooks/utils. Execute o notebook dentro do repositorio Saltim.")
sys.path.insert(0, str(UTILS_DIR))

from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression
from xgboost import XGBClassifier, XGBRegressor

from two_stage_common import run_training_notebook

In [2]:
threshold_models = {
    "Linear Regression": LinearRegression(),
    "XGBoost Regressor": XGBRegressor(),
    "Gradient Boosting Regressor": GradientBoostingRegressor(),
}

purchase_alert_models = {
    "Logistic Regression": LogisticRegression(),
    "XGBoost Classifier": XGBClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
}

In [3]:
results = run_training_notebook(
    notebook_id="02_linear",
    family="Linear",
    threshold_models=threshold_models,
    purchase_alert_models=purchase_alert_models,
)

display(results["threshold_metrics"])
display(results["purchase_alert_metrics"])
display(results["criticality_metrics"])
display(results["summary"][["notebook", "family", "sample_shape", "split_counts", "criticality_rates", "feature_count"]])

2026/05/29 10:09:26 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_02_linear_threshold_regression_linear_regression' already exists. Creating a new version of this model...
2026/05/29 10:09:30 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_02_linear_threshold_regression_linear_regression, version 2
Created version '2' of model 'saltim_two_stage_02_linear_threshold_regression_linear_regression'.

🏃 View run 02_linear - threshold_regression - Linear Regression at: http://localhost:5000/#/experiments/20/runs/a1a6b044027a4460b08f17cd7dab6c45
🧪 View experiment at: http://localhost:5000/#/experiments/20

2026/05/29 10:09:57 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_02_linear_threshold_regression_xgboost_regressor' already exists. Creating a new version of this model...
2026/05/29 10:10:00 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_02_linear_threshold_regression_xgboost_regressor, version 2
Created version '2' of model 'saltim_two_stage_02_linear_threshold_regression_xgboost_regressor'.

🏃 View run 02_linear - threshold_regression - XGBoost Regressor at: http://localhost:5000/#/experiments/20/runs/846050e3de5f4a7286ded5f3b97fc85b
🧪 View experiment at: http://localhost:5000/#/experiments/20

2026/05/29 10:10:57 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_02_linear_threshold_regression_gradient_boosting_regressor' already exists. Creating a new version of this model...
2026/05/29 10:10:59 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_02_linear_threshold_regression_gradient_boosting_regressor, version 2
Created version '2' of model 'saltim_two_stage_02_linear_threshold_regression_gradient_boosting_regressor'.

🏃 View run 02_linear - threshold_regression - Gradient Boosting Regressor at: http://localhost:5000/#/experiments/20/runs/fb47270ced464e19aa03cf99de75fcc0
🧪 View experiment at: http://localhost:5000/#/experiments/20

2026/05/29 10:11:04 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_02_linear_purchase_alert_classification_logistic_regression' already exists. Creating a new version of this model...
2026/05/29 10:11:07 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_02_linear_purchase_alert_classification_logistic_regression, version 2
Created version '2' of model 'saltim_two_stage_02_linear_purchase_alert_classification_logistic_regression'.

🏃 View run 02_linear - purchase_alert_classification - Logistic Regression at: http://localhost:5000/#/experiments/22/runs/5f34c0266bae4c9eb4fd27aafa8ed00c
🧪 View experiment at: http://localhost:5000/#/experiments/22

2026/05/29 10:11:28 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_02_linear_purchase_alert_classification_xgboost_classifier' already exists. Creating a new version of this model...
2026/05/29 10:11:31 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_02_linear_purchase_alert_classification_xgboost_classifier, version 2
Created version '2' of model 'saltim_two_stage_02_linear_purchase_alert_classification_xgboost_classifier'.

🏃 View run 02_linear - purchase_alert_classification - XGBoost Classifier at: http://localhost:5000/#/experiments/22/runs/06c934c41b864dd0b3a55f2812988c09
🧪 View experiment at: http://localhost:5000/#/experiments/22

2026/05/29 10:12:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_02_linear_purchase_alert_classification_gradient_boosting_classifier' already exists. Creating a new version of this model...
2026/05/29 10:12:22 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_02_linear_purchase_alert_classification_gradient_boosting_classifier, version 2
Created version '2' of model 'saltim_two_stage_02_linear_purchase_alert_classification_gradient_boosting_classifier'.

🏃 View run 02_linear - purchase_alert_classification - Gradient Boosting Classifier at: http://localhost:5000/#/experiments/22/runs/479e30ea6439452fa4e2b6defd31d6e8
🧪 View experiment at: http://localhost:5000/#/experiments/22

,notebook,family,stage,model,accuracy,balanced_accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,...,average_precision,rmse,mae,r2,run_id,model_uri,metric_artifact_path,prediction_artifact_path,summary_artifact_path,registered_model_name
0,02_linear,Linear,threshold_regression,Linear Regression,0.995568,0.991338,0.991523,0.991709,0.991338,0.845461,...,NaN,0.083430,0.057833,0.290209,a1a6b044027a4460b08f17cd7dab6c45,runs:/a1a6b044027a4460b08f17cd7dab6c45/model,evaluation/02_linear_linear_regression_thresho...,evaluation/02_linear_linear_regression_thresho...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_threshold_regressio...
1,02_linear,Linear,threshold_regression,XGBoost Regressor,0.997999,0.997306,0.996182,0.995066,0.997306,0.844460,...,NaN,0.046804,0.035411,0.776620,846050e3de5f4a7286ded5f3b97fc85b,runs:/846050e3de5f4a7286ded5f3b97fc85b/model,evaluation/02_linear_xgboost_regressor_thresho...,evaluation/02_linear_xgboost_regressor_thresho...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_threshold_regressio...
2,02_linear,Linear,threshold_regression,Gradient Boosting Regressor,0.997856,0.995711,0.995898,0.996086,0.995711,0.845461,...,NaN,0.051190,0.038618,0.732790,fb47270ced464e19aa03cf99de75fcc0,runs:/fb47270ced464e19aa03cf99de75fcc0/model,evaluation/02_linear_gradient_boosting_regress...,evaluation/02_linear_gradient_boosting_regress...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_threshold_regressio...

,notebook,family,stage,model,accuracy,balanced_accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,...,average_precision,rmse,mae,r2,run_id,model_uri,metric_artifact_path,prediction_artifact_path,summary_artifact_path,registered_model_name
0,02_linear,Linear,purchase_alert_classification,Logistic Regression,0.985132,0.980257,0.972056,0.964284,0.980257,0.838742,...,0.992742,NaN,NaN,NaN,5f34c0266bae4c9eb4fd27aafa8ed00c,runs:/5f34c0266bae4c9eb4fd27aafa8ed00c/model,evaluation/02_linear_logistic_regression_purch...,evaluation/02_linear_logistic_regression_purch...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_purchase_alert_clas...
1,02_linear,Linear,purchase_alert_classification,XGBoost Classifier,0.997570,0.994409,0.995345,0.996285,0.994409,0.846033,...,0.999782,NaN,NaN,NaN,06c934c41b864dd0b3a55f2812988c09,runs:/06c934c41b864dd0b3a55f2812988c09/model,evaluation/02_linear_xgboost_classifier_purcha...,evaluation/02_linear_xgboost_classifier_purcha...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_purchase_alert_clas...
2,02_linear,Linear,purchase_alert_classification,Gradient Boosting Classifier,0.997570,0.996297,0.995362,0.994432,0.996297,0.844603,...,0.994169,NaN,NaN,NaN,479e30ea6439452fa4e2b6defd31d6e8,runs:/479e30ea6439452fa4e2b6defd31d6e8/model,evaluation/02_linear_gradient_boosting_classif...,evaluation/02_linear_gradient_boosting_classif...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_purchase_alert_clas...

,notebook,family,stage,model,accuracy,balanced_accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,...,average_precision,rmse,mae,r2,run_id,model_uri,metric_artifact_path,prediction_artifact_path,summary_artifact_path,registered_model_name
0,02_linear,Linear,threshold_regression,Linear Regression,0.995568,0.991338,0.991523,0.991709,0.991338,0.845461,...,NaN,0.083430,0.057833,0.290209,a1a6b044027a4460b08f17cd7dab6c45,runs:/a1a6b044027a4460b08f17cd7dab6c45/model,evaluation/02_linear_linear_regression_thresho...,evaluation/02_linear_linear_regression_thresho...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_threshold_regressio...
1,02_linear,Linear,threshold_regression,XGBoost Regressor,0.997999,0.997306,0.996182,0.995066,0.997306,0.844460,...,NaN,0.046804,0.035411,0.776620,846050e3de5f4a7286ded5f3b97fc85b,runs:/846050e3de5f4a7286ded5f3b97fc85b/model,evaluation/02_linear_xgboost_regressor_thresho...,evaluation/02_linear_xgboost_regressor_thresho...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_threshold_regressio...
2,02_linear,Linear,threshold_regression,Gradient Boosting Regressor,0.997856,0.995711,0.995898,0.996086,0.995711,0.845461,...,NaN,0.051190,0.038618,0.732790,fb47270ced464e19aa03cf99de75fcc0,runs:/fb47270ced464e19aa03cf99de75fcc0/model,evaluation/02_linear_gradient_boosting_regress...,evaluation/02_linear_gradient_boosting_regress...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_threshold_regressio...
3,02_linear,Linear,purchase_alert_classification,Logistic Regression,0.985132,0.980257,0.972056,0.964284,0.980257,0.838742,...,0.992742,NaN,NaN,NaN,5f34c0266bae4c9eb4fd27aafa8ed00c,runs:/5f34c0266bae4c9eb4fd27aafa8ed00c/model,evaluation/02_linear_logistic_regression_purch...,evaluation/02_linear_logistic_regression_purch...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_purchase_alert_clas...
4,02_linear,Linear,purchase_alert_classification,XGBoost Classifier,0.997570,0.994409,0.995345,0.996285,0.994409,0.846033,...,0.999782,NaN,NaN,NaN,06c934c41b864dd0b3a55f2812988c09,runs:/06c934c41b864dd0b3a55f2812988c09/model,evaluation/02_linear_xgboost_classifier_purcha...,evaluation/02_linear_xgboost_classifier_purcha...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_purchase_alert_clas...
5,02_linear,Linear,purchase_alert_classification,Gradient Boosting Classifier,0.997570,0.996297,0.995362,0.994432,0.996297,0.844603,...,0.994169,NaN,NaN,NaN,479e30ea6439452fa4e2b6defd31d6e8,runs:/479e30ea6439452fa4e2b6defd31d6e8/model,evaluation/02_linear_gradient_boosting_classif...,evaluation/02_linear_gradient_boosting_classif...,evaluation/02_linear_run_summary.json,saltim_two_stage_02_linear_purchase_alert_clas...

,notebook,family,sample_shape,split_counts,criticality_rates,feature_count
0,02_linear,Linear,"[61750, 105]","{'train': 45480, 'validation': 9275, 'test': 6...","{'OK': 0.8442753036437247, 'Alerta de compra':...",73