# Notebook 3 - Modelos Baseados em Arvores

Pipeline two-stage com Random Forest como modelo principal e XGBoost/Gradient Boosting como baselines.

In [1]:
from pathlib import Path
import sys

NOTEBOOK_DIR = Path.cwd()
UTILS_DIR = next(
    (candidate / "utils" for candidate in [NOTEBOOK_DIR, *NOTEBOOK_DIR.parents] if (candidate / "utils").is_dir()),
    None,
)
if UTILS_DIR is None:
    raise RuntimeError("Nao encontrei ml/notebooks/utils. Execute o notebook dentro do repositorio Saltim.")
sys.path.insert(0, str(UTILS_DIR))

from sklearn.ensemble import (
    GradientBoostingClassifier,
    GradientBoostingRegressor,
    RandomForestClassifier,
    RandomForestRegressor,
)
from xgboost import XGBClassifier, XGBRegressor

from two_stage_common import run_training_notebook

In [2]:
threshold_models = {
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBoost Regressor": XGBRegressor(),
    "Gradient Boosting Regressor": GradientBoostingRegressor(),
}

purchase_alert_models = {
    "Random Forest Classifier": RandomForestClassifier(),
    "XGBoost Classifier": XGBClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
}

In [3]:
results = run_training_notebook(
    notebook_id="03_tree_ensembles",
    family="Arvores",
    threshold_models=threshold_models,
    purchase_alert_models=purchase_alert_models,
)

display(results["threshold_metrics"])
display(results["purchase_alert_metrics"])
display(results["criticality_metrics"])
display(results["summary"][["notebook", "family", "sample_shape", "split_counts", "criticality_rates", "feature_count"]])

2026/05/29 10:19:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_03_tree_ensembles_threshold_regression_random_forest_regressor' already exists. Creating a new version of this model...
2026/05/29 10:19:17 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_03_tree_ensembles_threshold_regression_random_forest_regressor, version 2
Created version '2' of model 'saltim_two_stage_03_tree_ensembles_threshold_regression_random_forest_regressor'.

🏃 View run 03_tree_ensembles - threshold_regression - Random Forest Regressor at: http://localhost:5000/#/experiments/23/runs/a8a30d7e5b80486f9288e75dd7d2242e
🧪 View experiment at: http://localhost:5000/#/experiments/23

2026/05/29 10:19:26 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_03_tree_ensembles_threshold_regression_xgboost_regressor' already exists. Creating a new version of this model...
2026/05/29 10:19:28 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_03_tree_ensembles_threshold_regression_xgboost_regressor, version 2
Created version '2' of model 'saltim_two_stage_03_tree_ensembles_threshold_regression_xgboost_regressor'.

🏃 View run 03_tree_ensembles - threshold_regression - XGBoost Regressor at: http://localhost:5000/#/experiments/23/runs/4f20fde6854640ef9c26b55be30d8af9
🧪 View experiment at: http://localhost:5000/#/experiments/23

2026/05/29 10:20:11 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_03_tree_ensembles_threshold_regression_gradient_boosting_regressor' already exists. Creating a new version of this model...
2026/05/29 10:20:14 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_03_tree_ensembles_threshold_regression_gradient_boosting_regressor, version 2
Created version '2' of model 'saltim_two_stage_03_tree_ensembles_threshold_regression_gradient_boosting_regressor'.

🏃 View run 03_tree_ensembles - threshold_regression - Gradient Boosting Regressor at: http://localhost:5000/#/experiments/23/runs/27d6e7bd81f54ea8b52e51ce6ed6bc1a
🧪 View experiment at: http://localhost:5000/#/experiments/23

2026/05/29 10:20:21 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_03_tree_ensembles_purchase_alert_classification_random_forest_classifier' already exists. Creating a new version of this model...
2026/05/29 10:20:23 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_03_tree_ensembles_purchase_alert_classification_random_forest_classifier, version 2
Created version '2' of model 'saltim_two_stage_03_tree_ensembles_purchase_alert_classification_random_forest_classifier'.

🏃 View run 03_tree_ensembles - purchase_alert_classification - Random Forest Classifier at: http://localhost:5000/#/experiments/24/runs/50486c6cf6ef4050bb465bb8888a0a81
🧪 View experiment at: http://localhost:5000/#/experiments/24

2026/05/29 10:20:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_03_tree_ensembles_purchase_alert_classification_xgboost_classifier' already exists. Creating a new version of this model...
2026/05/29 10:20:30 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_03_tree_ensembles_purchase_alert_classification_xgboost_classifier, version 2
Created version '2' of model 'saltim_two_stage_03_tree_ensembles_purchase_alert_classification_xgboost_classifier'.

🏃 View run 03_tree_ensembles - purchase_alert_classification - XGBoost Classifier at: http://localhost:5000/#/experiments/24/runs/8ef094e762b34fb293e9917c1ad2d321
🧪 View experiment at: http://localhost:5000/#/experiments/24

2026/05/29 10:21:13 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'saltim_two_stage_03_tree_ensembles_purchase_alert_classification_gradient_boosting_classifier' already exists. Creating a new version of this model...
2026/05/29 10:21:15 INFO mlflow.store.model_registry.abstract_store: Waiting up to 120 seconds for model version to finish creation. Model name: saltim_two_stage_03_tree_ensembles_purchase_alert_classification_gradient_boosting_classifier, version 2

🏃 View run 03_tree_ensembles - purchase_alert_classification - Gradient Boosting Classifier at: http://localhost:5000/#/experiments/24/runs/d0c2092912a74b31bac9c3dea9205d51
🧪 View experiment at: http://localhost:5000/#/experiments/24

Created version '2' of model 'saltim_two_stage_03_tree_ensembles_purchase_alert_classification_gradient_boosting_classifier'.

,notebook,family,stage,model,accuracy,balanced_accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,...,average_precision,rmse,mae,r2,run_id,model_uri,metric_artifact_path,prediction_artifact_path,summary_artifact_path,registered_model_name
0,03_tree_ensembles,Arvores,threshold_regression,Random Forest Regressor,0.998856,0.998191,0.997815,0.997440,0.998191,0.845032,...,NaN,0.046589,0.035292,0.778663,a8a30d7e5b80486f9288e75dd7d2242e,runs:/a8a30d7e5b80486f9288e75dd7d2242e/model,evaluation/03_tree_ensembles_random_forest_reg...,evaluation/03_tree_ensembles_random_forest_reg...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_threshold_r...
1,03_tree_ensembles,Arvores,threshold_regression,XGBoost Regressor,0.997999,0.997306,0.996182,0.995066,0.997306,0.844460,...,NaN,0.046804,0.035411,0.776620,4f20fde6854640ef9c26b55be30d8af9,runs:/4f20fde6854640ef9c26b55be30d8af9/model,evaluation/03_tree_ensembles_xgboost_regressor...,evaluation/03_tree_ensembles_xgboost_regressor...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_threshold_r...
2,03_tree_ensembles,Arvores,threshold_regression,Gradient Boosting Regressor,0.997856,0.995711,0.995898,0.996086,0.995711,0.845461,...,NaN,0.051189,0.038615,0.732801,27d6e7bd81f54ea8b52e51ce6ed6bc1a,runs:/27d6e7bd81f54ea8b52e51ce6ed6bc1a/model,evaluation/03_tree_ensembles_gradient_boosting...,evaluation/03_tree_ensembles_gradient_boosting...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_threshold_r...

,notebook,family,stage,model,accuracy,balanced_accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,...,average_precision,rmse,mae,r2,run_id,model_uri,metric_artifact_path,prediction_artifact_path,summary_artifact_path,registered_model_name
0,03_tree_ensembles,Arvores,purchase_alert_classification,Random Forest Classifier,0.997856,0.995711,0.995898,0.996086,0.995711,0.845461,...,0.999708,NaN,NaN,NaN,50486c6cf6ef4050bb465bb8888a0a81,runs:/50486c6cf6ef4050bb465bb8888a0a81/model,evaluation/03_tree_ensembles_random_forest_cla...,evaluation/03_tree_ensembles_random_forest_cla...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_purchase_al...
1,03_tree_ensembles,Arvores,purchase_alert_classification,XGBoost Classifier,0.997570,0.994409,0.995345,0.996285,0.994409,0.846033,...,0.999782,NaN,NaN,NaN,8ef094e762b34fb293e9917c1ad2d321,runs:/8ef094e762b34fb293e9917c1ad2d321/model,evaluation/03_tree_ensembles_xgboost_classifie...,evaluation/03_tree_ensembles_xgboost_classifie...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_purchase_al...
2,03_tree_ensembles,Arvores,purchase_alert_classification,Gradient Boosting Classifier,0.997570,0.996297,0.995362,0.994432,0.996297,0.844603,...,0.994169,NaN,NaN,NaN,d0c2092912a74b31bac9c3dea9205d51,runs:/d0c2092912a74b31bac9c3dea9205d51/model,evaluation/03_tree_ensembles_gradient_boosting...,evaluation/03_tree_ensembles_gradient_boosting...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_purchase_al...

,notebook,family,stage,model,accuracy,balanced_accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,...,average_precision,rmse,mae,r2,run_id,model_uri,metric_artifact_path,prediction_artifact_path,summary_artifact_path,registered_model_name
0,03_tree_ensembles,Arvores,threshold_regression,Random Forest Regressor,0.998856,0.998191,0.997815,0.997440,0.998191,0.845032,...,NaN,0.046589,0.035292,0.778663,a8a30d7e5b80486f9288e75dd7d2242e,runs:/a8a30d7e5b80486f9288e75dd7d2242e/model,evaluation/03_tree_ensembles_random_forest_reg...,evaluation/03_tree_ensembles_random_forest_reg...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_threshold_r...
1,03_tree_ensembles,Arvores,threshold_regression,XGBoost Regressor,0.997999,0.997306,0.996182,0.995066,0.997306,0.844460,...,NaN,0.046804,0.035411,0.776620,4f20fde6854640ef9c26b55be30d8af9,runs:/4f20fde6854640ef9c26b55be30d8af9/model,evaluation/03_tree_ensembles_xgboost_regressor...,evaluation/03_tree_ensembles_xgboost_regressor...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_threshold_r...
2,03_tree_ensembles,Arvores,threshold_regression,Gradient Boosting Regressor,0.997856,0.995711,0.995898,0.996086,0.995711,0.845461,...,NaN,0.051189,0.038615,0.732801,27d6e7bd81f54ea8b52e51ce6ed6bc1a,runs:/27d6e7bd81f54ea8b52e51ce6ed6bc1a/model,evaluation/03_tree_ensembles_gradient_boosting...,evaluation/03_tree_ensembles_gradient_boosting...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_threshold_r...
3,03_tree_ensembles,Arvores,purchase_alert_classification,Random Forest Classifier,0.997856,0.995711,0.995898,0.996086,0.995711,0.845461,...,0.999708,NaN,NaN,NaN,50486c6cf6ef4050bb465bb8888a0a81,runs:/50486c6cf6ef4050bb465bb8888a0a81/model,evaluation/03_tree_ensembles_random_forest_cla...,evaluation/03_tree_ensembles_random_forest_cla...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_purchase_al...
4,03_tree_ensembles,Arvores,purchase_alert_classification,XGBoost Classifier,0.997570,0.994409,0.995345,0.996285,0.994409,0.846033,...,0.999782,NaN,NaN,NaN,8ef094e762b34fb293e9917c1ad2d321,runs:/8ef094e762b34fb293e9917c1ad2d321/model,evaluation/03_tree_ensembles_xgboost_classifie...,evaluation/03_tree_ensembles_xgboost_classifie...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_purchase_al...
5,03_tree_ensembles,Arvores,purchase_alert_classification,Gradient Boosting Classifier,0.997570,0.996297,0.995362,0.994432,0.996297,0.844603,...,0.994169,NaN,NaN,NaN,d0c2092912a74b31bac9c3dea9205d51,runs:/d0c2092912a74b31bac9c3dea9205d51/model,evaluation/03_tree_ensembles_gradient_boosting...,evaluation/03_tree_ensembles_gradient_boosting...,evaluation/03_tree_ensembles_run_summary.json,saltim_two_stage_03_tree_ensembles_purchase_al...

,notebook,family,sample_shape,split_counts,criticality_rates,feature_count
0,03_tree_ensembles,Arvores,"[61750, 105]","{'train': 45480, 'validation': 9275, 'test': 6...","{'OK': 0.8442753036437247, 'Alerta de compra':...",73