# Notebook 1 - Algoritmos Baseados em Distancia

Pipeline two-stage com KNN como modelo principal e XGBoost/Gradient Boosting como baselines.

In [1]:
from pathlib import Path
import sys

NOTEBOOK_DIR = Path.cwd()
if (NOTEBOOK_DIR / "two_stage_common.py").exists():
    sys.path.insert(0, str(NOTEBOOK_DIR))
else:
    sys.path.insert(0, str((Path("data") / "notebooks").resolve()))

from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from xgboost import XGBClassifier, XGBRegressor

from two_stage_common import run_training_notebook

In [2]:
threshold_models = {
    "KNN Regressor": KNeighborsRegressor(),
    "XGBoost Regressor": XGBRegressor(),
    "Gradient Boosting Regressor": GradientBoostingRegressor(),
}

purchase_alert_models = {
    "KNN Classifier": KNeighborsClassifier(),
    "XGBoost Classifier": XGBClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
}

In [3]:
results = run_training_notebook(
    notebook_id="01_knn",
    family="Distancia",
    threshold_models=threshold_models,
    purchase_alert_models=purchase_alert_models,
)

display(results["threshold_metrics"])
display(results["purchase_alert_metrics"])
display(results["criticality_metrics"])
display(results["summary"][["notebook", "family", "sample_shape", "split_counts", "criticality_rates", "feature_count"]])

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,01_knn,Distancia,threshold_regression,KNN Regressor,ml/artifacts/two_stage/01_knn_knn_regressor_th...,ml/artifacts/two_stage/metrics/01_knn_knn_regr...,0.993567,0.987667,0.988967,0.986379,0.846319,0.153681,0.153681,,0.071022,0.048211,0.485638
1,01_knn,Distancia,threshold_regression,XGBoost Regressor,ml/artifacts/two_stage/01_knn_xgboost_regresso...,ml/artifacts/two_stage/metrics/01_knn_xgboost_...,0.997999,0.996182,0.995066,0.997306,0.844460,0.155540,0.155540,,0.046804,0.035411,0.776620
2,01_knn,Distancia,threshold_regression,Gradient Boosting Regressor,ml/artifacts/two_stage/01_knn_gradient_boostin...,ml/artifacts/two_stage/metrics/01_knn_gradient...,0.997856,0.995898,0.996086,0.995711,0.845461,0.154539,0.154539,,0.051189,0.038615,0.732801

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,01_knn,Distancia,purchase_alert_classification,KNN Classifier,ml/artifacts/two_stage/01_knn_knn_classifier_p...,ml/artifacts/two_stage/metrics/01_knn_knn_clas...,0.982988,0.966934,0.974913,0.959356,0.851465,0.148535,0.148535,,NaN,NaN,NaN
1,01_knn,Distancia,purchase_alert_classification,XGBoost Classifier,ml/artifacts/two_stage/01_knn_xgboost_classifi...,ml/artifacts/two_stage/metrics/01_knn_xgboost_...,0.997570,0.995345,0.996285,0.994409,0.846033,0.153967,0.153967,,NaN,NaN,NaN
2,01_knn,Distancia,purchase_alert_classification,Gradient Boosting Classifier,ml/artifacts/two_stage/01_knn_gradient_boostin...,ml/artifacts/two_stage/metrics/01_knn_gradient...,0.997570,0.995362,0.994432,0.996297,0.844603,0.155397,0.155397,,NaN,NaN,NaN

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,01_knn,Distancia,threshold_regression,KNN Regressor,ml/artifacts/two_stage/01_knn_knn_regressor_th...,ml/artifacts/two_stage/metrics/01_knn_knn_regr...,0.993567,0.987667,0.988967,0.986379,0.846319,0.153681,0.153681,,0.071022,0.048211,0.485638
1,01_knn,Distancia,threshold_regression,XGBoost Regressor,ml/artifacts/two_stage/01_knn_xgboost_regresso...,ml/artifacts/two_stage/metrics/01_knn_xgboost_...,0.997999,0.996182,0.995066,0.997306,0.844460,0.155540,0.155540,,0.046804,0.035411,0.776620
2,01_knn,Distancia,threshold_regression,Gradient Boosting Regressor,ml/artifacts/two_stage/01_knn_gradient_boostin...,ml/artifacts/two_stage/metrics/01_knn_gradient...,0.997856,0.995898,0.996086,0.995711,0.845461,0.154539,0.154539,,0.051189,0.038615,0.732801
3,01_knn,Distancia,purchase_alert_classification,KNN Classifier,ml/artifacts/two_stage/01_knn_knn_classifier_p...,ml/artifacts/two_stage/metrics/01_knn_knn_clas...,0.982988,0.966934,0.974913,0.959356,0.851465,0.148535,0.148535,,NaN,NaN,NaN
4,01_knn,Distancia,purchase_alert_classification,XGBoost Classifier,ml/artifacts/two_stage/01_knn_xgboost_classifi...,ml/artifacts/two_stage/metrics/01_knn_xgboost_...,0.997570,0.995345,0.996285,0.994409,0.846033,0.153967,0.153967,,NaN,NaN,NaN
5,01_knn,Distancia,purchase_alert_classification,Gradient Boosting Classifier,ml/artifacts/two_stage/01_knn_gradient_boostin...,ml/artifacts/two_stage/metrics/01_knn_gradient...,0.997570,0.995362,0.994432,0.996297,0.844603,0.155397,0.155397,,NaN,NaN,NaN

,notebook,family,sample_shape,split_counts,criticality_rates,feature_count
0,01_knn,Distancia,"[61750, 105]","{'train': 45480, 'validation': 9275, 'test': 6...","{'OK': 0.8442753036437247, 'Alerta de compra':...",73