# Notebook 2 - Modelos Lineares

Pipeline two-stage com Regressao Logistica no Stage 1, Regressao Linear no Stage 2 e XGBoost/Gradient Boosting como baselines.

In [1]:
from pathlib import Path
import sys

NOTEBOOK_DIR = Path.cwd()
if (NOTEBOOK_DIR / "two_stage_common.py").exists():
    sys.path.insert(0, str(NOTEBOOK_DIR))
else:
    sys.path.insert(0, str((Path("data") / "notebooks").resolve()))

from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression
from xgboost import XGBClassifier, XGBRegressor

from two_stage_common import run_training_notebook

In [2]:
threshold_models = {
    "Linear Regression": LinearRegression(),
    "XGBoost Regressor": XGBRegressor(),
    "Gradient Boosting Regressor": GradientBoostingRegressor(),
}

purchase_alert_models = {
    "Logistic Regression": LogisticRegression(),
    "XGBoost Classifier": XGBClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
}

In [3]:
results = run_training_notebook(
    notebook_id="02_linear",
    family="Linear",
    threshold_models=threshold_models,
    purchase_alert_models=purchase_alert_models,
)

display(results["threshold_metrics"])
display(results["purchase_alert_metrics"])
display(results["criticality_metrics"])
display(results["summary"][["notebook", "family", "sample_shape", "split_counts", "criticality_rates", "feature_count"]])

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,02_linear,Linear,threshold_regression,Linear Regression,ml/artifacts/two_stage/02_linear_linear_regres...,ml/artifacts/two_stage/metrics/02_linear_linea...,0.995568,0.991523,0.991709,0.991338,0.845461,0.154539,0.154539,,0.083430,0.057833,0.290209
1,02_linear,Linear,threshold_regression,XGBoost Regressor,ml/artifacts/two_stage/02_linear_xgboost_regre...,ml/artifacts/two_stage/metrics/02_linear_xgboo...,0.997999,0.996182,0.995066,0.997306,0.844460,0.155540,0.155540,,0.046804,0.035411,0.776620
2,02_linear,Linear,threshold_regression,Gradient Boosting Regressor,ml/artifacts/two_stage/02_linear_gradient_boos...,ml/artifacts/two_stage/metrics/02_linear_gradi...,0.997856,0.995898,0.996086,0.995711,0.845461,0.154539,0.154539,,0.051189,0.038615,0.732801

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,02_linear,Linear,purchase_alert_classification,Logistic Regression,ml/artifacts/two_stage/02_linear_logistic_regr...,ml/artifacts/two_stage/metrics/02_linear_logis...,0.985132,0.972056,0.964284,0.980257,0.838742,0.161258,0.161258,,NaN,NaN,NaN
1,02_linear,Linear,purchase_alert_classification,XGBoost Classifier,ml/artifacts/two_stage/02_linear_xgboost_class...,ml/artifacts/two_stage/metrics/02_linear_xgboo...,0.997570,0.995345,0.996285,0.994409,0.846033,0.153967,0.153967,,NaN,NaN,NaN
2,02_linear,Linear,purchase_alert_classification,Gradient Boosting Classifier,ml/artifacts/two_stage/02_linear_gradient_boos...,ml/artifacts/two_stage/metrics/02_linear_gradi...,0.997570,0.995362,0.994432,0.996297,0.844603,0.155397,0.155397,,NaN,NaN,NaN

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,02_linear,Linear,threshold_regression,Linear Regression,ml/artifacts/two_stage/02_linear_linear_regres...,ml/artifacts/two_stage/metrics/02_linear_linea...,0.995568,0.991523,0.991709,0.991338,0.845461,0.154539,0.154539,,0.083430,0.057833,0.290209
1,02_linear,Linear,threshold_regression,XGBoost Regressor,ml/artifacts/two_stage/02_linear_xgboost_regre...,ml/artifacts/two_stage/metrics/02_linear_xgboo...,0.997999,0.996182,0.995066,0.997306,0.844460,0.155540,0.155540,,0.046804,0.035411,0.776620
2,02_linear,Linear,threshold_regression,Gradient Boosting Regressor,ml/artifacts/two_stage/02_linear_gradient_boos...,ml/artifacts/two_stage/metrics/02_linear_gradi...,0.997856,0.995898,0.996086,0.995711,0.845461,0.154539,0.154539,,0.051189,0.038615,0.732801
3,02_linear,Linear,purchase_alert_classification,Logistic Regression,ml/artifacts/two_stage/02_linear_logistic_regr...,ml/artifacts/two_stage/metrics/02_linear_logis...,0.985132,0.972056,0.964284,0.980257,0.838742,0.161258,0.161258,,NaN,NaN,NaN
4,02_linear,Linear,purchase_alert_classification,XGBoost Classifier,ml/artifacts/two_stage/02_linear_xgboost_class...,ml/artifacts/two_stage/metrics/02_linear_xgboo...,0.997570,0.995345,0.996285,0.994409,0.846033,0.153967,0.153967,,NaN,NaN,NaN
5,02_linear,Linear,purchase_alert_classification,Gradient Boosting Classifier,ml/artifacts/two_stage/02_linear_gradient_boos...,ml/artifacts/two_stage/metrics/02_linear_gradi...,0.997570,0.995362,0.994432,0.996297,0.844603,0.155397,0.155397,,NaN,NaN,NaN

,notebook,family,sample_shape,split_counts,criticality_rates,feature_count
0,02_linear,Linear,"[61750, 105]","{'train': 45480, 'validation': 9275, 'test': 6...","{'OK': 0.8442753036437247, 'Alerta de compra':...",73