# Notebook 3 - Modelos Baseados em Arvores

Pipeline two-stage com Random Forest como modelo principal e XGBoost/Gradient Boosting como baselines.

In [1]:
from pathlib import Path
import sys

NOTEBOOK_DIR = Path.cwd()
if (NOTEBOOK_DIR / "two_stage_common.py").exists():
    sys.path.insert(0, str(NOTEBOOK_DIR))
else:
    sys.path.insert(0, str((Path("data") / "notebooks").resolve()))

from sklearn.ensemble import (
    GradientBoostingClassifier,
    GradientBoostingRegressor,
    RandomForestClassifier,
    RandomForestRegressor,
)
from xgboost import XGBClassifier, XGBRegressor

from two_stage_common import run_training_notebook

In [2]:
threshold_models = {
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBoost Regressor": XGBRegressor(),
    "Gradient Boosting Regressor": GradientBoostingRegressor(),
}

purchase_alert_models = {
    "Random Forest Classifier": RandomForestClassifier(),
    "XGBoost Classifier": XGBClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
}

In [3]:
results = run_training_notebook(
    notebook_id="03_tree_ensembles",
    family="Arvores",
    threshold_models=threshold_models,
    purchase_alert_models=purchase_alert_models,
)

display(results["threshold_metrics"])
display(results["purchase_alert_metrics"])
display(results["criticality_metrics"])
display(results["summary"][["notebook", "family", "sample_shape", "split_counts", "criticality_rates", "feature_count"]])

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,03_tree_ensembles,Arvores,threshold_regression,Random Forest Regressor,ml/artifacts/two_stage/03_tree_ensembles_rando...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.998713,0.997543,0.996981,0.998106,0.844889,0.155111,0.155111,,0.046893,0.035387,0.775765
1,03_tree_ensembles,Arvores,threshold_regression,XGBoost Regressor,ml/artifacts/two_stage/03_tree_ensembles_xgboo...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997999,0.996182,0.995066,0.997306,0.844460,0.155540,0.155540,,0.046804,0.035411,0.776620
2,03_tree_ensembles,Arvores,threshold_regression,Gradient Boosting Regressor,ml/artifacts/two_stage/03_tree_ensembles_gradi...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997856,0.995898,0.996086,0.995711,0.845461,0.154539,0.154539,,0.051190,0.038618,0.732790

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,03_tree_ensembles,Arvores,purchase_alert_classification,Random Forest Classifier,ml/artifacts/two_stage/03_tree_ensembles_rando...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997999,0.996173,0.996173,0.996173,0.845318,0.154682,0.154682,,NaN,NaN,NaN
1,03_tree_ensembles,Arvores,purchase_alert_classification,XGBoost Classifier,ml/artifacts/two_stage/03_tree_ensembles_xgboo...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997570,0.995345,0.996285,0.994409,0.846033,0.153967,0.153967,,NaN,NaN,NaN
2,03_tree_ensembles,Arvores,purchase_alert_classification,Gradient Boosting Classifier,ml/artifacts/two_stage/03_tree_ensembles_gradi...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997570,0.995362,0.994432,0.996297,0.844603,0.155397,0.155397,,NaN,NaN,NaN

,notebook,family,stage,model,artifact_path,prediction_path,accuracy,f1_macro,precision_macro,recall_macro,taxa_ok,taxa_alerta_compra,taxa_necessita_compra,warnings,rmse,mae,r2
0,03_tree_ensembles,Arvores,threshold_regression,Random Forest Regressor,ml/artifacts/two_stage/03_tree_ensembles_rando...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.998713,0.997543,0.996981,0.998106,0.844889,0.155111,0.155111,,0.046893,0.035387,0.775765
1,03_tree_ensembles,Arvores,threshold_regression,XGBoost Regressor,ml/artifacts/two_stage/03_tree_ensembles_xgboo...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997999,0.996182,0.995066,0.997306,0.844460,0.155540,0.155540,,0.046804,0.035411,0.776620
2,03_tree_ensembles,Arvores,threshold_regression,Gradient Boosting Regressor,ml/artifacts/two_stage/03_tree_ensembles_gradi...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997856,0.995898,0.996086,0.995711,0.845461,0.154539,0.154539,,0.051190,0.038618,0.732790
3,03_tree_ensembles,Arvores,purchase_alert_classification,Random Forest Classifier,ml/artifacts/two_stage/03_tree_ensembles_rando...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997999,0.996173,0.996173,0.996173,0.845318,0.154682,0.154682,,NaN,NaN,NaN
4,03_tree_ensembles,Arvores,purchase_alert_classification,XGBoost Classifier,ml/artifacts/two_stage/03_tree_ensembles_xgboo...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997570,0.995345,0.996285,0.994409,0.846033,0.153967,0.153967,,NaN,NaN,NaN
5,03_tree_ensembles,Arvores,purchase_alert_classification,Gradient Boosting Classifier,ml/artifacts/two_stage/03_tree_ensembles_gradi...,ml/artifacts/two_stage/metrics/03_tree_ensembl...,0.997570,0.995362,0.994432,0.996297,0.844603,0.155397,0.155397,,NaN,NaN,NaN

,notebook,family,sample_shape,split_counts,criticality_rates,feature_count
0,03_tree_ensembles,Arvores,"[61750, 105]","{'train': 45480, 'validation': 9275, 'test': 6...","{'OK': 0.8442753036437247, 'Alerta de compra':...",73